apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - storageclass.yaml

patches:
  - target:
      kind: ServiceAccount
    patch: |-
      - op: add
        path: /metadata/annotations/iam.gke.io~1gcp-service-account
        value: internal-agents-sa@PROJECT_ID.iam.gserviceaccount.com

commonLabels:
  cloud: gke
  deployment-type: cloud-agnostic
