apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - storageclass.yaml

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/metadata/labels/azure.workload.identity~1use
        value: "true"

commonLabels:
  cloud: aks
  deployment-type: cloud-agnostic
